### ISSUE TITLE
臺中市南區興大路145號 -> returns 4024 (instead of 40227)

### ISSUE THREAD

**Issue by s864372002** [moskytw/zipcodetw#17]
(前面的 issue 都是這種格式我就照抄了XD)

這是中興大學的地址，興大路在南區的部份只有它不是4024開頭，40227似乎被規則忽略了QQ
![image](https://user-images.githubusercontent.com/11780364/58549600-77bd7900-823e-11e9-922b-248dfa2791f6.png)

**Comment by moskytw** [comment]
Should be fixed in a version.
