### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by c6209c6209** [moskytw/zipcodetw#24]
When I was running on .py file, everything went great. However, after converting my .py to .exe and executing the .exe file, it pops out the error message.

```
File "site-packages\zipcodetw\util.py", line 313, in method_wrapper
sqlite3.OperationalError: unable to open database file
```
Is there any solution?

**Comment by moskytw** [comment]
You may need to ship with the SQLite db file it built. See https://github.com/moskytw/zipcodetw/blob/dev/zipcodetw/builder.py#L34.
