### ISSUE TITLE
台北市復興南路二段 -> returns 10 (instead of 106)

### ISSUE THREAD

**Issue by timdream** [moskytw/zipcodetw#6]
復興南路二段 is entirely in 大安區, so a better result would be 106 instead of 10.

I can see a few pull requests on level 1 token but I am not sure they are related or not.

**Comment by moskytw** [comment]
thanks! if you use “台北市大安區復興南路二段”, you will get the right result. It's a known issue. I will try to fix it by a upgradation of structure this year (I hope).

**Comment by moskytw** [comment]
Noted to my own to-do list. Thanks for reporting. I will fix it in the next version.
