### ISSUE TITLE
苗栗縣苗栗市聯大路2號 -> return 360 (instead of 36063)

### ISSUE THREAD

**Issue by hearsilent** [moskytw/zipcodetw#7]
剛好測到這特殊測資，就來開 Issue 了 :+1:

**Comment by moskytw** [comment]
不好意思，遲回了。謝謝你的回報，最近會改一個版本，剛剛把它加到測試集了！

**Comment by moskytw** [comment]
把他加入到個人 to-do 了，之後會改一個新版！

**Comment by s864372002** [comment]
@hearsilent
聯合大學的地址是 **苗栗縣苗栗市「聯大」2號** 才對，沒有「路」喔
「聯大路」不存在XD

**Comment by hearsilent** [comment]
@s864372002 原來如此 XD
